### ISSUE TITLE
zabbix_bot does not use token

### ISSUE THREAD

**Issue by silkeh** [lordievader/matrix-zabbix-bot#5]
It looks like the token in the configuration is not actually used by the `zabbox_bot` part, like one would expect.

Using only the token in the configuration results in the following error:

```
A MatrixRequestError occured during sync.
Exception in thread Thread-455:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/matrix_client/client.py", line 473, in listen_forever
    self._sync(timeout_ms)
  File "/usr/local/lib/python3.7/dist-packages/matrix_client/client.py", line 555, in _sync
    response = self.api.sync(self.sync_token, timeout_ms, filter=self.sync_filter)
  File "/usr/local/lib/python3.7/dist-packages/matrix_client/api.py", line 105, in sync
    api_path=MATRIX_V2_API_PATH)
  File "/usr/local/lib/python3.7/dist-packages/matrix_client/api.py", line 691, in _send
    code=response.status_code, content=response.text
matrix_client.errors.MatrixRequestError: 401: {"errcode":"M_MISSING_TOKEN","error":"Missing access token"}
```

**Comment by lordievader** [comment]
~~After some digging I found that the python-matrix-sdk does not support token based logins to begin with. What confuses me is why I've added code for a token based login.~~

~~Path to solution seems to me: open a PR in the python-matrix-sdk to add support for token based logins, and backport the support into this project.~~

Not sure what was going on there... python-matrix-sdk does support token based logins. It is used within `matrix.py`.
The python-matrix-bot does not, however.
